development:
  adapter: postgresql
  encoding: utf8
  database: bulletin_app_development
  pool: 5
  username: postgres
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: bulletin_app_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: bulletin_app_production
  pool: 5
  username: postgres
  password:

cucumber:
  <<: *TEST
